services:
  # Next.js app service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nextjs-app
    ports:
      - '3000:3000'
    # depends_on:
    # environment:
    #COMMAND: [ "pm2-runtime", "start", "npm", "--", "start" ]
